### ISSUE TITLE
Typo in generate_keys.sh

### ISSUE THREAD

**Issue by mdcg** [ksuaning-au/mqtt_cert_auth#1]
Hihi, how are you?

There is a "small typo" in the command to generate "server.crt". Below is the command written correctly

```
openssl x509 -req -in server.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out server.crt -days 360;
```

**Comment by ksuaning-au** [comment]
Thanks for letting me know. I have just updated the readme.
